[package]
name = "git-publish"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
clap = { version = "3.2.20", features = ["derive"] }
git2 = "0.14"
git2_credentials = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
